---
title: "Title"
subtitle: "Alexandra Orczyk, Vy Nguyen, Xiyue Huang"
graphics: yes
output: 
        pdf_document:
         toc: false
         number_sections: true
urlcolor: blue
header-includes:
- \usepackage{amsmath,amsfonts,amssymb}
- \usepackage{multicol,graphicx,hyperref,xcolor}
- \usepackage{setspace} \doublespacing
fontsize: 11pt

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract: 

During the COVID-19 pandemic, Tens of millions of people have been infected with COVID-19, emphasizing the importance of safe and effective vaccines. IIn December 2020, Pfizer and BioNTech were granted permission to distribute their BNT162b2 vaccine, a nucleoside-modified RNA vaccine encoding the SARS-CoV-2 spike protein. To test its efficacy, a placebo-controlled, observer-blinded trial was conducted with 35,092 participants aged 16 and older, randomized in a 1:1 ratio to receive two doses of BNT162b2 or placebo, 21 days apart. The study targeted 170 infections resulting in 8 cases in the vaccine group and 162 in the placebo group, indicating a vaccine efficacy of 95%. A Bayesian beta-binomial model confirmed this efficacy, with a 95% confidence interval of [90.3%, 97.6%] and a probability greater than 0.9999 that the efficacy exceeds 30%, indicating the vaccine's outstanding efficacy. In this project, we will conduct a similar analysis and approach the result by using different methods to measure the safety and efficacy of the vaccine. 

# Keywords:

COVID-19, BNT162b2, Vaccine efficacy, Binomial distribution, Hypothesis testing, Confidence Interval

# Introduction:

Prior studies on the efficacy of the various COVID-19 vaccines, particiularly the Pfizer and Moderna mRNA vaccines, have found them to be highly effective at lowering infection, lowering the severity of symptoms, and preventing hospitalization and death. For example, Cai, Peng, et.al calculated a 95% confidence interval of $93.65$%–$95.40$% as an estimate of the vaccine efficacy rate of the mRNA vaccines, which was defined as $\frac{\text{Risk among unvaccinated group} - \text{risk among vaccinated group}}{\text{Risk among unvaccinated group}}$. Similarly, a systematic review by Grana, Ghosn, et. al found "high-certainty evidence" that the BioNTech/Pfizer vaccine reduced both the prevalence of symptomatic COVID-19 and symptom severity compared to placebo. However, they found lower efficacy against newer COVID-19 variants. Although there are some estimates that make the vaccines seem less effective, such as the Absolute Risk Reduction of 0.9% for the Pfizer vaccine reported by Olliaro, Torreele, et.al, however, since this statistic reports the difference in infection rates between the unvaccinated and vaccinated population, it has the flaw of reporting a higher degree of efficacy for the vaccines tested in populations with a higher rate of Covid-19, which is why most studies use other estimators. Overall, the majority of studies report a high degree of efficacy for the mRNA Covid-19 vaccines.

# Statistical Methods:


# Discussion/Conclusion:

# References:
https://www.cell.com/molecular-therapy-family/molecular-therapy/fulltext/S1525-0016(21)00395-6#secsectitle0025
https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD015477/full
https://www.thelancet.com/journals/ebiom/article/PIIS2666-5247(21)00069-0/fulltext

# Appendix: